Algoritmo "Operadores Lógicos e Relacionais"
// Disciplina   : [Algoritmo e Lógica de Programação]
// Professor   : Guanabara 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/10/2021
Var
// Seção de Declarações das variáveis 

   A, B, C: Inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

         A  <- 2
         B  <- 3
         C  <- 5
         Escreva (C>=B^A)


Fimalgoritmo