Algoritmo "ex-8"
// 
//  
// Descrição   :  8) Desenvolva um programa que leia uma
//distância em metros e mostre os valores relativos em outras
//medidas.
//Ex:
//Digite uma distância em metros: 185.72
//A distância de 85.7m corresponde a:
//0.18572Km  1.8572Hm
//18.572Dam  1857.2dm
// 18572.0cm  185720.0mm



// Autor(a)    : luxasfn
// Data atual  : 11/14/2022
Var
// Seção de Declarações das variáveis 




Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo