algoritmo "ex-7"
// Disciplina: [Algoritmo e Lógica de Programação]
// Professor: Guanabara
// Autor: Luxasfn
// Data: 01/10/2021

{}

// Seção de Declarações 
var
   n1, dobro, terco: real
inicio
// Seção de Comandos

         escreva("Digite um numero: ")
         leia(n1)
         dobro <- n1 * 2
         terco <- n1 / 3
         escreval("O dobro de ",n1, " é ", dobro)
         escreva("A terça parte de ",n1, " é ",terco)
         
fimalgoritmo
