algoritmo "ex-9"
// Disciplina: [Algoritmo e Lógica de Programação]
// Professor: Guanabara
// Autor: Luxasfn
// Data: 01/10/2021

{}

// Seção de Declarações 
var
 dinheiro, dolar: real
inicio
// Seção de Comandos 
         Escreval("Dinheiro disponível: ")
         leia(dinheiro)
         dolar <- dinheiro*3.45
         escreva("Com ", dinheiro ," é possível comprar ", dolar ," dolares")
fimalgoritmo
