algoritmo "ex-2"
// Disciplina: [Algoritmo e Lógica de Programação]
// Professor: Guanabara
// Autor: Luxasfn
// Data: 01/10/2021

{2) Faça um programa que leia o nome de uma pessoa e mostre uma mensagem
de boasvindas para ela:
Ex:
Qual é o seu nome? João da Silva
Olá João da Silva, é um prazer te conhecer!}

// Seção de Declarações
var
N: caractere
inicio
// Seção de Comandos
   escreva("Qual é o seu nome? ")
   leia(n)
   escreva("Ola, ",N ,", e um prazer te conhecer!")
fimalgoritmo
